### 등록
POST http://localhost:8080/residents
Content-Type: application/json

{
  "residentSerialNumber": "8",
  "name": "이민서",
  "residentRegistrationNumber": "990704-******",
  "genderCode": "남",
  "birthDate": "1999-07-04 12:12:00",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "광주광역시 남구 백운동 루엔시티",
  "deathDate": "",
  "deathPlaceCode": "",
  "deathPlaceAddress": ""
}

### 수정
PUT http://localhost:8080/residents/8
Content-Type: application/json

{
  "registrationBaseAddress" : "판교 NHN 두레이"
}
